# Options for the Basalt SLAM Tracker

# Show GUI
show-gui=0

# Ground-truth camera calibration used for simulation.
cam-calib="basalt_calibration.json"

# Path to config file.
config-path="slam_config.json"

# Path to folder where marginalization data will be stored.
marg-data=""

# Poll and print for queue sizes.
print-queue=0

# Whether to use a double or single precision pipeline.
use-double=0
